services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
            args:
                - USER_UID=1000
                - USER_GID=1000
        container_name: 'python'
        stdin_open: true
        ports:
            - 8080:8080
        volumes:
            - ./:/app
            - venv:/app/.venv
        command: ['rye', 'run', 'uvicorn', 'src.main:app', '--host', '0.0.0.0', '--port', '8080', '--reload']

volumes:
    venv:
