services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_UID=10001
                - USER_GID=10001
        container_name: 'python'
        stdin_open: true
        tty: true
        ports:
            - 8888:8888
        volumes:
            - ./:/app
            - venv:/app/.venv
        command:
            [
                'poetry',
                'run',
                'jupyter',
                'notebook',
                '--ip',
                '0.0.0.0',
                '--port',
                '8888',
                '--NotebookApp.token',
                'token'
            ]

volumes:
    venv:
