services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
            args:
                - USER_UID=1000
                - USER_GID=1000
        container_name: 'python'
        stdin_open: true
        ports:
            - 8888:8888
        tty: true
        volumes:
            - ./:/app
            - venv:/app/.venv
        command:
            ['rye', 'run', 'jupyter', 'notebook', '--ip', '0.0.0.0', '--port', '8888', '--NotebookApp.token', 'token']

volumes:
    venv:
