services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_UID=10001
                - USER_GID=10001
        container_name: 'python'
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
            - venv:/app/.venv
        command: ['/bin/bash']

volumes:
    venv:
