version: '3.3'

services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_UID=1000
                - USER_GID=1000
        container_name: 'python'
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
            - venv:/app/.venv
        command: ['/bin/bash']

volumes:
    venv:
